version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3308:3306 # HOST: CONTAINER
    environment:
      MYSQL_ROOT_PASSQORD: zucchini
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
