version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3308:3306 # HOST: CONTAINER
    environment:
      MYSQL_ROOT_PASSQORD: zucchini
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  frontend:
    build:
      context: ./zucchini_frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "80:80"

  backend:
    build:
      context: ./zucchini_backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8081:8080"
