version: "3"

services:
  # db:
  #   image: mysql:8.0
  #   volumes:
  #     - zucchini:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: zucchini
  #     MYSQL_DATABASE: zucchini
  #   ports:
  #     - "3030:3030"

  backend:
    image: "./zucchini_backend"
    container_name: "backend"
    ports:
      - "8081:8081"
    # depends_on:
    #   - db

  frontend:
    image: "./zucchini_frontend"
    container_name: "frontend"
    ports:
      - "80:80"
    depends_on:
      - backend

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx/Dockerfile
  #   ports:
  #     - "80:80"
# volumes:
#   zucchini:
