version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3308:3306 # HOST: CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: zucchini
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - front-connection

  redis:
    image: redis
    command: redis-server /usr/local/conf/redis.conf
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"

  frontend:
    build:
      context: ./zucchini_frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - front-connection

  backend:
    build:
      context: ./zucchini_backend
      dockerfile: Dockerfile
    container_name: backend-container
    restart: always
    ports:
      - "8200:8200"
    networks:
      - front-connection

networks:
  front-connection:
    driver: bridge
